name: Generate Docs

on:
  # File paths to consider in the event. Optional; defaults to all
  push:
    branches:    # Array of patterns that match refs/heads
      - master     # Push events on master branch
      # - test-dev
  #     - 'releases/*' # Push events to branches matching refs/heads/releases/*
  #     - '!refs/pull/*'
  #   tags:        # Array of patterns that match refs/tags.
  #     - v1         # Push events to v1 tag
    paths:       # Push events containing matching files
      - 'source/*.md'
      - '.github/workflows/gen-docs.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig

    - uses: actions/checkout@v2
      with:
        # submodules: true
        persist-credentials: false
        token: ${{ secrets.PAT }}

    - name: Setup git user
      env:
        ACCESS_TOKEN: ${{ secrets.PAT }}
      run: |
        if [ -z "$COMMIT_EMAIL" ]
        then
          COMMIT_EMAIL="${GITHUB_ACTOR}@users.noreply.github.com"
        fi

        if [ -z "$COMMIT_NAME" ]
        then
          COMMIT_NAME="${GITHUB_ACTOR}"
        fi
        git config --global credential.helper store && \
        git config --global user.email "${COMMIT_EMAIL}" && \
        git config --global user.name "${COMMIT_NAME}" && \
        REPOSITORY_PATH="https://${ACCESS_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

    - name: show contents
      run: ls -l source

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@1.1.3
      env:
       FOLDER: build/html
       BRANCH: gh-pages
       BUILD_SCRIPT: |
        apt-get install -y graphviz doxygen-gui rsync python3-pip;
        python3 -m pip install --upgrade Sphinx recommonmark;
        ls -lrt;
        make html
       ACCESS_TOKEN: ${{ secrets.PAT }}


